name: VLT Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  export-kicad:
    env:
      KICAD_BASE_FILENAME: "VLT"
      KICAD_BASE_FOLDER: "./pcb"
      KICAD_SCHEMATIC_FILE_EXTENSION: "kicad_sch"
      KICAD_PCB_FILE_EXTENSION: "kicad_pcb"
      KICAD_OUTPUT_FOLDER: "./output"
      KIBOT_CONFIG_FILE: ".kibot/build.kibot.yaml"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Prepare output directory
      run: |
        mkdir -p ${{ env.KICAD_OUTPUT_FOLDER }}
        cp -r ${{ env.KICAD_BASE_FOLDER }} ${{ env.KICAD_OUTPUT_FOLDER }}/kicad
        cp ./LICENSE ${{ env.KICAD_OUTPUT_FOLDER }}

    - name: Run KiBOT
      uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: ${{ env.KIBOT_CONFIG_FILE }}
        dir: ${{ env.KICAD_OUTPUT_FOLDER }}
        schema: "${{ env.KICAD_BASE_FOLDER }}/${{ env.KICAD_BASE_FILENAME }}.${{ env.KICAD_SCHEMATIC_FILE_EXTENSION }}"
        board: "${{ env.KICAD_BASE_FOLDER }}/${{ env.KICAD_BASE_FILENAME }}.${{ env.KICAD_PCB_FILE_EXTENSION }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v7
      with:
        name: kicad-export
        path: ${{ env.KICAD_OUTPUT_FOLDER }}
        retention-days: 1

  export-freecad:
    env:
      FREECAD_VERSION: "1.1.1"
      FREECAD_FILENAME: "./mechanical/housing.FCStd"
      FREECAD_OUTPUT_FOLDER: "./output"
      FREECAD_PARTTYPE: "PartDesign::Body"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Prepare output directory
      run: |
        mkdir -p ${{ env.FREECAD_OUTPUT_FOLDER }}
        cp -r ./mechanical ${{ env.FREECAD_OUTPUT_FOLDER }}
        cp ./LICENSE ${{ env.FREECAD_OUTPUT_FOLDER }}

    - name: Install FreeCAD
      run: |
          wget https://github.com/FreeCAD/FreeCAD/releases/download/${{ env.FREECAD_VERSION }}/FreeCAD_${{ env.FREECAD_VERSION }}-Linux-x86_64-py311.AppImage
          chmod 0777 FreeCAD_${{ env.FREECAD_VERSION }}-Linux-x86_64-py311.AppImage
          ./FreeCAD_${{ env.FREECAD_VERSION }}-Linux-x86_64-py311.AppImage --appimage-extract
    
    - name: Get FreeCAD Export
      uses: actions/checkout@v7
      with:
        repository: 0x007E/pyfreecadexport
        path: ./pyfreecadexport
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Export STEP Files
      run: |
          ./squashfs-root/usr/bin/python ./pyfreecadexport/src/pyfreecadexport.py -f "${{ env.FREECAD_FILENAME }}" -p "${{ env.FREECAD_PARTTYPE }}" -d "${{ env.FREECAD_OUTPUT_FOLDER }}" -e "step" -l "squashfs-root/usr/lib/"
          ./squashfs-root/usr/bin/python ./pyfreecadexport/src/pyfreecadexport.py -f "${{ env.FREECAD_FILENAME }}" -p "${{ env.FREECAD_PARTTYPE }}" -d "${{ env.FREECAD_OUTPUT_FOLDER }}" -e "stl" -l "squashfs-root/usr/lib/"
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v7
      with:
        name: freecad-export
        path: ${{ env.FREECAD_OUTPUT_FOLDER }}
        retention-days: 1